### ISSUE TITLE
Colorit library name

### ISSUE THREAD

**Issue by widewind2015** [griloHBG/find-in-devicetree#1]
On Ubuntu 20.04 with python3.8, the colorit library is installed by `pip install color-it` instead of colorit.

**Comment by griloHBG** [comment]
Thanks!

Solved in 6fcb2aecc44381b85f5ceab1d2e794cff29ee3da

Now [README.md](https://github.com/griloHBG/find_in_devicetree/blob/main/README.md) shows how to install each package.
